version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5010:5010"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://13.62.45.198:5010
    container_name: frontend
    restart: always
    ports:
      - "5174:5174"
    depends_on:
      - backend
