

events {}

http {
    #increase clinet body size limit to 10 megabytes
    client_max_body_size 10M;

    server{
        listen 80;

    # when accessing the root URL, serve the frontend application
        location / {
            proxy_pass http://frontend:5174;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
        }

    # when accessing /api, forward requests to the backend application
        location /api/ {
            proxy_pass http://backend:5010;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        location /nginx-health {
            return 200 'nginx is healthy';
            add_header Content-Type text/plain;
        }
    }
}